#ifdef __single
	INTEGER, PARAMETER, PRIVATE :: MK      = KIND(1E0)
	INTEGER, PARAMETER, PRIVATE :: MKC     = KIND(CMPLX(1E0,1E0,MK))
#elif __double
	INTEGER, PARAMETER, PRIVATE :: MK      = KIND(1D0)
	INTEGER, PARAMETER, PRIVATE :: MKC     = KIND(CMPLX(1D0,1D0,MK))
#else
	INTEGER, PARAMETER, PRIVATE :: MK      = KIND(1D0)
	INTEGER, PARAMETER, PRIVATE :: MKC     = KIND(CMPLX(1D0,1D0,MK))
#endif
	INTEGER, PARAMETER, PRIVATE :: MAXCHAR = 256
